### ISSUE TITLE
(UndefinedFunctionError) undefined function: :yaml.load_file/2

### ISSUE THREAD

**Issue by ccblaisdell** [trestrantham/ex_figaro#1]
After adding ex_figaro to my mix file and fetching the app's dependencies, I get this error when running `iex -S mix`.

```
** (Mix) Could not start application figaro: Figaro.start(:normal, []) returned an error: shutdown: failed to start child: Figaro
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: :yaml.load_file/2
            :yaml.load_file("/Users/ccblaisdell/elixir/dota/config/application.yml", [:implicit_atoms])
            (figaro) lib/figaro/yaml.ex:3: Figaro.Yaml.parse_file/1
            (figaro) lib/figaro.ex:40: Figaro.load_config/1
            (figaro) lib/figaro.ex:20: Figaro.start_link/0
            (stdlib) supervisor.erl:314: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:297: :supervisor.start_children/3
            (stdlib) supervisor.erl:263: :supervisor.init_children/2
            (stdlib) gen_server.erl:306: :gen_server.init_it/6
```

I tried putting figaro in the dependencies using the hex format shown in the readme, and also using the github format, but it seems to not be installing the :yaml library. What do I need to do to make sure I have all the requirements ready to use ex_figaro?

**Comment by D1plo1d** [comment]
Had the same issue. Changing my mixfile deps to:
```
      {:figaro, github: 'trestrantham/ex_figaro', branch: 'master'},
```
fixed the issue for me.
